platform :ios, '10.0'

source 'git@github.com:tokend/ios-specs.git'
source 'https://github.com/CocoaPods/Specs.git'

use_modular_headers!

def main_pods
  pod 'DLCryptoKit', path: '../'
end

target 'DLCryptoKit_Example' do
  main_pods
end

target 'DLCryptoKit_Tests' do
  inherit! :search_paths

  main_pods
end
